SOA-MVC/Controllers/AssetsController.cs
using Domain;
using Microsoft.AspNetCore.Mvc;
using Service.IService;
using Service.Service;
using Microsoft.AspNetCore.Authorization;

namespace SOA_MVC.Controllers
{
    [Authorize]
    public class AssetsController : Controller
    {

        private readonly IAsset _assetService;

        public AssetsController(IAsset asset)
        {
            _assetService = asset;
        }

        public IActionResult Index()
        {
            var lista = _assetService.GetAssets();
            return View(lista);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Activo activo)
        {
            var result = _assetService.CreateAssets(activo);

            if (result > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(activo);
            }
        }

        public IActionResult Edit(int id)
        {

            Activo activo = _assetService.GetAsset(id);
            return View(activo);
        }
        [HttpPost]
        public IActionResult Edit(Activo activo)
        {
            var result = _assetService.UpdateAssets(activo);

            if (result > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(activo);
            }
        }

        [HttpPost]
        public IActionResult Delete(Activo activo)
        {
            var result = _assetService.DeleteAssets(activo);

            if (result > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");

            }
        }
    }
}

SOA-MVC/Controllers/AssetsEmployesController.cs
using Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Service.IService;
using Service.Service.Correo;
using System.Security.Claims;

namespace SOA_MVC.Controllers
{
    [Authorize]
    public class AssetsEmployesController : Controller
    {
        private readonly IAssetEmploye _assetEmployeService;
        private readonly IAsset _assetService;
        private readonly IEmploye _employeService;
        private readonly ICorreo _correoService;


        public AssetsEmployesController(IAssetEmploye assetEmploye, IAsset asset, IEmploye employe, ICorreo correoService)
        {
            _assetEmployeService = assetEmploye;
            _assetService = asset;
            _employeService = employe;
            _correoService = correoService;
        }
        public IActionResult Index()
        {
            var lista = _assetEmployeService.GetAssetsEmployes();
            return View(lista);
        }

        public IActionResult Create()
        {
            var empleados = _employeService.GetEmployes();
            var activos = _assetService.GetAssetsUnused();

            ViewBag.Empleados = empleados;
            ViewBag.Activos = activos;

            return View();
        }

        [HttpPost]
        public IActionResult Create(Activo_Empleado activoEmpleado)
        {
            var result = _assetEmployeService.CreateAssetsEmployes(activoEmpleado);

            if (result > 0)
            {
                _assetService.SetAssetAsUSed(activoEmpleado.Id_Activo);
                _correoService.SendEmail(activoEmpleado, HttpContext.User.Identity as ClaimsIdentity);
                return RedirectToAction("Index");
            }
            else
            {
                var empleados = _employeService.GetEmployes();
                var activos = _assetService.GetAssetsUnused();

                ViewBag.Empleados = empleados;
                ViewBag.Activos = activos;
                return View(activoEmpleado);
            }
        }

        public IActionResult Edit(int id)
        {

            Activo_Empleado activoEmpleado = _assetEmployeService.GetAssetEmploye(id);
            return View(activoEmpleado);
        }
        [HttpPost]
        public IActionResult Edit(Activo_Empleado activoEmpleado)
        {
            var result = _assetEmployeService.UpdateAssetsEmployes(activoEmpleado);

            if (result > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(activoEmpleado);
            }
        }

        [HttpPost]
        public IActionResult Delete(Activo_Empleado activoEmpleado)
        {
            _assetService.SetAssetAsUnuSed(activoEmpleado.Id_Activo);
            var result = _assetEmployeService.DeleteAssetsEmployes(activoEmpleado);

            if (result > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");

            }
        }
    }
}

SOA-MVC/Controllers/EmployesController.cs
using Domain;
using Microsoft.AspNetCore.Mvc;
using Service.IService;
using Microsoft.AspNetCore.Authorization;

namespace SOA_MVC.Controllers
{
    [Authorize]
    public class EmployesController : Controller
    { 

        private readonly IEmploye _employeService;

        public EmployesController(IEmploye employe)
        {
            _employeService = employe;
        }
        public IActionResult Index()
        {
            var lista = _employeService.GetEmployes();
            return View(lista);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Empleado empleado)
        {
            var result = _employeService.CreateEmployes(empleado);
            
            if (result > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(empleado);
            }
        }

        public IActionResult Edit(int id)
        {

            Empleado empleado = _employeService.GetEmploye(id);
            return View(empleado);
        }
        [HttpPost]
        public IActionResult Edit(Empleado empleado)
        {
            var result = _employeService.UpdateEmployes(empleado);

            if (result > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(empleado);
            }
        }

        [HttpPost]
        public IActionResult Delete(Empleado empleado)
        {
            var result = _employeService.DeleteEmployes(empleado);

            if (result > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");

            }
        }
    }
}

SOA-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SOA_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SOA_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SOA_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employes" asp-action="Index">Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assets" asp-action="Index">Activos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AssetsEmployes" asp-action="Index">Activos-Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="CerrarSesion">Cerrar Sesion</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SOA_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>